export type model = {
  appid: string;
  name: string;
  developer: string;
  publisher: string;
  positive: number;
  negative: number;
  ccu: number;
  short_description: string;
  _free: boolean;
  capsule_image: string;
  website: string;
  discount_percent: number;
  initial_formatted: string;
  final_formatted: string;
  mp4: string;
  windows: boolean;
  mac: boolean;
  linux: boolean;
  release_date: string;
};
